# Generated by Django 5.0.6 on 2024-05-26 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='unit',
        ),
    ]
